#!/usr/bin/env sh

# For this to work you must configure sudo such that it will be able to run the command without password.
# See this wiki page for information:
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

# global settings
yabai -m config                                 \
    layout                       bsp            \
    window_placement             second_child   \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   10             \
    mouse_follows_focus          on             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    window_shadow                float          \
    window_opacity               on             \
    active_window_opacity        1.0            \
    normal_window_opacity        0.5            \
    ;

# focus_follows_mouse          off            \
    # window_origin_display        default        \
    # window_zoom_persist          on             \
    # window_animation_duration    0.0            \
    # window_animation_frame_rate  120            \
    # window_opacity_duration      0.0            \
    # insert_feedback_color        0xffd75f5f     \
    # split_ratio                  0.50           \
    # split_type                   auto           \
    # auto_balance                 off            \
    # mouse_modifier               fn             \
    # ;


yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Finder$" manage=off


echo "yabai configuration loaded.."


